//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\steve\Konves.ChordPro\src\Konves.ChordPro.Grammar\ChordProParser.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Konves.ChordPro {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ChordProParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public interface IChordProParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ChordProParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDocument([NotNull] ChordProParser.DocumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ChordProParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDocument([NotNull] ChordProParser.DocumentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ChordProParser.songLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSongLine([NotNull] ChordProParser.SongLineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ChordProParser.songLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSongLine([NotNull] ChordProParser.SongLineContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ChordProParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] ChordProParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ChordProParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] ChordProParser.BlockContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ChordProParser.word"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWord([NotNull] ChordProParser.WordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ChordProParser.word"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWord([NotNull] ChordProParser.WordContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ChordProParser.syllable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSyllable([NotNull] ChordProParser.SyllableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ChordProParser.syllable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSyllable([NotNull] ChordProParser.SyllableContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ChordProParser.chord"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChord([NotNull] ChordProParser.ChordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ChordProParser.chord"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChord([NotNull] ChordProParser.ChordContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ChordProParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirective([NotNull] ChordProParser.DirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ChordProParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirective([NotNull] ChordProParser.DirectiveContext context);
}
} // namespace Konves.ChordPro
